title: OverCUE
description: Cue preparation controls for rekordbox with XPPen ACK05
theme: jekyll-theme-cayman
show_downloads: false
github:
  is_project_page: true
  repository_url: https://github.com/albasimia/OverCUE
  owner_url: https://github.com/albasimia
  owner_name: albasimia
exclude:
  - current-spec.md
  - spec.md
